/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

  //用一个列表来表示侧边栏的内容，列表中内容用逗号分隔
  knowledge: [
    //这是指intro.mdx
    'intro',
    //数据结构文件夹
    {
      type: 'category',
      label: '数据结构',
      link: {
        type: 'generated-index',
        title: '数据结构知识点',
        description: "整理刷题和考研过程中学到的数据结构",
      }, 
      items: [
        {
          type: 'autogenerated',
          dirName: 'data structure', 
        }
      ],
    },
    //Python学习文件夹
    {
      type: 'category',
      label: 'Python学习',
      link: {
        type: 'generated-index',
        title: 'Python',
        description: '根据官方文档学习的记录',
        keywords: ['Python']
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'Python learning',
        }
      ]
    },
  ],

  algorithm: [
    'intro',
    {
      type: 'category',
      label: 'Acwing',
      link: {
        type: 'generated-index',
        title: 'Acwing',
        description: '根据Acwing算法课程的内容做的笔记，包括题目，算法用途，思路，复杂度以及代码等内容',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'algorithm/Acwing'
        }
      ]
    }
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
